ci: print docker image used for testing

diff --git a/.github/workflows/reusable-workflow.yml b/.github/workflows/reusable-workflow.yml
--- a/.github/workflows/reusable-workflow.yml
+++ b/.github/workflows/reusable-workflow.yml
@@ -38,7 +38,6 @@ on:
       docker_image:
         description: 'Docker image for the a3p chain to use in testing'
         required: false
-        default: ghcr.io/agoric/agoric-3-proposals:latest
         type: string
 
 jobs:
@@ -59,6 +58,15 @@ jobs:
         with:
           project_id: 'simulationlab'
           workload_identity_provider: 'projects/60745596728/locations/global/workloadIdentityPools/github/providers/dapp-inter'
+
+      - name: Docker Image Used For E2E Testing
+        run: |
+          if [ -z "${{ inputs.docker_image }}" ]; then
+            echo "Error: Docker image not provided."
+            exit 1
+          else
+            echo "Docker Image: ${{ inputs.docker_image }}"
+          fi
 
       - name: Run e2e tests
         run: ${{ inputs.docker_compose_command }}
